### ISSUE TITLE
0.0.17 bug - connection refused from gateway

### ISSUE THREAD

**Issue by kmw0410** [0xfurai/peekaping#27]
when i click `sign up` to register or try logging in with any account, `An error occurred during registration ` is shown on the web, and `connection refused` appears in the gateway container logs
how can i fix this?

![Image](https://github.com/user-attachments/assets/71d80489-764c-4b3e-9d99-6edb44de151a)

```
gateway-1  | 2025/06/28 09:27:03 [error] 29#29: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.100, server: , request: "POST /api/v1/auth/register HTTP/1.1", upstream: "http://172.23.0.2:8034/api/v1/auth/register", host: "192.168.0.32:8383", referrer: "http://192.168.0.32:8383/register"
gateway-1  | 192.168.0.100 - - [28/Jun/2025:09:27:03 +0000] "POST /api/v1/auth/register HTTP/1.1" 502 559 "http://192.168.0.32:8383/register" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"
```

**Comment by 0xfurai** [comment]
Can you please attach docker compose file you use?

**Comment by kmw0410** [comment]
```yml
networks:
  appnet:

services:
  migrate:
    image: 0xfurai/peekaping-migrate:latest
    restart: "no"
    env_file:
      - .env
    environment:
      - DB_TYPE=sqlite
      - DB_NAME=/app/data/peekaping.db
    volumes:
      - ./.data/sqlite:/app/data

  server:
    image: 0xfurai/peekaping-server:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_TYPE=sqlite
      - DB_NAME=/app/data/peekaping.db
      - MODE=prod
    volumes:
      - ./.data/sqlite:/app/data
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - appnet

  web:
    image: 0xfurai/peekaping-web:latest
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - appnet

  gateway:
    image: nginx:latest
    ports:
      - "8383:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
      - web
    networks:
      - appnet
```
