### ISSUE TITLE
Gateway exit 0 after Docker Reboot

### ISSUE THREAD

**Issue by Lautsprecher** [0xfurai/peekaping#33]
Hiho,

feedback ahead.
Im running into
Gateway exit 0 after Docker Reboot while my Proxmox Host Backups.

![Image](https://github.com/user-attachments/assets/e3f98ac7-454e-423d-a1e2-9395b9b7e01e)

Greetings and thanks :)

```
Gateway log:
docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
192.168.2.125 - - [30/Jun/2025:14:29:15 +0000] "GET /notification-channels/be1fe6d9-7162-4b9b-afce-dda18dfb57cf/edit HTTP/1.1" 200 492 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"
```

```
networks:
  appnet:

services:
  migrate:
    image: 0xfurai/peekaping-migrate:latest
    restart: "no"
    env_file:
      - stack.env
    environment:
      - DB_TYPE=sqlite
      - DB_NAME=/app/data/peekaping.db
    volumes:
      - /volume1/docker/peekaping/data/sqlite:/app/data

  server:
    image: 0xfurai/peekaping-server:latest
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      - DB_TYPE=sqlite
      - DB_NAME=/app/data/peekaping.db
      - MODE=prod
    volumes:
      - /volume1/docker/peekaping/data/sqlite:/app/data
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - appnet

  web:
    image: 0xfurai/peekaping-web:latest
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - appnet

  gateway:
    image: nginx:latest
    ports:
      - "8383:80"
    volumes:
      - /volume1/docker/peekaping/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
      - web
    networks:
      - appnet

```

```
events {}
http {
  upstream server  { server server:8034; }
  upstream web { server web:80; }

  server {
    listen 80;

    # Pure API calls
    location /api/ {
      proxy_pass         http://server;
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
    }

    # socket.io
    location /socket.io/ {
      proxy_pass http://server;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    # Everything else → static SPA
    location / {
      proxy_pass http://web;
    }
  }
}
```
