### ISSUE TITLE
An error occurred during registration

### ISSUE THREAD

**Issue by 0PandaDEV** [0xfurai/peekaping#7]
The only log message I get is:
```log
web-1      | 192.168.1.117 - - [23/Jun/2025:11:22:14 +0000] "POST /api/v1/auth/register HTTP/1.1" 405 157 "http://192.168.1.103:8000/register" "Mozilla/5.0 (X11; Linux x86_64; rv:140.0) Gecko/20100101 Firefox/140.0" "-"
```

I purposefully chose to use a volume, but I also tried it with the DB as a folder.
```yml
services:
  mongodb:
    image: mongo:7
    restart: always
    ports:
      - "${DB_PORT}:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongodb:/data/db
    networks:
      - appnet

  server:
    image: 0xfurai/peekaping-server:latest
    env_file:
      - .env
    depends_on:
      - mongodb
    environment:
      DB_HOST: mongodb
      DB_PORT: 27017
    networks:
      - appnet

  web:
    image: 0xfurai/peekaping-web:latest
    ports:
      - "8000:80"
    depends_on:
      - server
    networks:
      - appnet

volumes:
  mongodb:

networks:
  appnet:
```

```env
DB_USER=root
DB_PASS=153cca...
DB_NAME=peekaping
DB_HOST=localhost
DB_PORT=27017

PORT=8000
CLIENT_URL="https://peekaping.pandadev.net"
ACCESS_TOKEN_EXPIRED_IN=1m
ACCESS_TOKEN_SECRET_KEY=2350e0...
REFRESH_TOKEN_EXPIRED_IN=60m
REFRESH_TOKEN_SECRET_KEY=80058f...
MODE=prod # logging
TZ="Europe/Zurich"
```

![Image](https://github.com/user-attachments/assets/9def3c08-46ac-4133-99d0-81382c032f81)
